package modelo;
// Generated 23 feb 2023 11:16:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cicloformativo generated by hbm2java
 */
@Entity
@Table(name = "cicloformativo", catalog = "instituto")
public class Ciclo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -968218944706376944L;
	private Integer idCiclo;
	private String nombre;
	private Integer horas;

	public Ciclo() {
	}

	public Ciclo(String nombreCiclo, Integer horas) {
		this.nombre = nombreCiclo;
		this.horas = horas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCiclo", unique = true, nullable = false)
	public Integer getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(Integer idCiclo) {
		this.idCiclo = idCiclo;
	}

	@Column(name = "nombreCiclo", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombreCiclo) {
		this.nombre = nombreCiclo;
	}

	@Column(name = "horas")
	public Integer getHoras() {
		return this.horas;
	}

	public void setHoras(Integer horas) {
		this.horas = horas;
	}

}
