package modelo;
// Generated 23 feb 2023 11:16:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", catalog = "instituto")
public class Direccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5721188078965661249L;
	private Integer id;
	private String calle;
	private Integer numero;
	private String poblacion;
	private int idProvincia;

	public Direccion() {
	}

	public Direccion(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	public Direccion(String calle, Integer numero, String poblacion, int idProvincia) {
		this.calle = calle;
		this.numero = numero;
		this.poblacion = poblacion;
		this.idProvincia = idProvincia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "calle")
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "poblacion")
	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	@Column(name = "idProvincia", nullable = false)
	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

}
