package modelo;
// Generated 23 feb 2023 11:16:20 by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", catalog = "instituto")
public class Modulo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8568593237402343894L;
	private Integer idModulo;
	private String nombre;
	private Set<Profesor> profesors = new HashSet<Profesor>(0);

	public Modulo() {
	}

	public Modulo(String nombre) {
		this.nombre = nombre;
	}

	public Modulo(String nombre, Set<Profesor> profesors) {
		this.nombre = nombre;
		this.profesors = profesors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModulo", unique = true, nullable = false)
	public Integer getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(Integer idModulo) {
		this.idModulo = idModulo;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(mappedBy = "modulos")
	public Set<Profesor> getProfesors() {
		return this.profesors;
	}

	public void setProfesors(Set<Profesor> profesors) {
		this.profesors = profesors;
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
